# https://pabluc.medium.com/raspberrypi-github-actions-ci-cd-1dc098b4c7d3
name: Unstable release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy from"
        required: true
        default: "main"

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE: ghcr.io/greenm4x/hexguess-server
  WEB_IMAGE: ghcr.io/greenm4x/hexguess-web

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./backend/Dockerfile
            image: ghcr.io/greenm4x/hexguess-server
            path: ./backend
            name: backend
          - dockerfile: ./frontend/Dockerfile
            image: ghcr.io/greenm4x/hexguess-web
            path: ./frontend
            name: frontend
    name: Build & deploy ${{ matrix.name }} image 🚀
    permissions:
      contents: read
      packages: write

    steps:
      # Access Repository in action
      - name: Checkout ⬇️
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Get current date ⌛
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get commit hash ⚙️
        id: sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # action can be useful if you want to add emulation support with QEMU
      # to be able to build against more platforms.
      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v3
      # action will create and boot a builder using by default the docker-container builder driver.
      # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push Hexguess Server images 🛠️
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.dockerfile }}
          tags: |
            ${{ matrix.image }}:${{ github.event_name == 'push' && github.ref_name == 'main' && 'latest' || github.event.inputs.branch || github.ref_name }}
            ${{ matrix.image }}:${{ github.event.inputs.branch || github.ref_name }}.${{ steps.date.outputs.date }}.${{ steps.sha.outputs.sha }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          push: true

  run-on-pi:
    runs-on: self-hosted # Raspberry Pi
    # environment: production
    needs: docker-build-and-push
    steps:
      # Checkout repo to get docker compose file (can maybe provided from previous job later)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest server image
        run: |
          if [ "${{ github.event_name == 'push' && github.ref_name == 'main' }}" = "true" ]; then
            docker pull ${{ env.SERVER_IMAGE }}:latest
          else
            docker pull ${{ env.SERVER_IMAGE }}:${{ github.event.inputs.branch || github.ref_name }}
          fi

      - name: Pull latest web image
        run: |
          if [ "${{ github.event_name == 'push' && github.ref_name == 'main' }}" = "true" ]; then
            docker pull ${{ env.WEB_IMAGE }}:latest
          else
            docker pull ${{ env.WEB_IMAGE }}:${{ github.event.inputs.branch || github.ref_name }}
          fi

      - name: Run docker image
        run: docker compose up -d --build

      - name: Remove old unused image
        run: docker image prune -a -f --filter "label=name=hexguess"
